### ISSUE TITLE
When adding new subobject to array: inherit dataType, accessType, PDOmapping?

### ISSUE THREAD

**Issue by s-fuchs** [robincornelius/libedssharp#43]
I'm talking about this [line](https://github.com/robincornelius/libedssharp/blob/9df069dcaa2a6a1d52a3345f67604923559769ba/EDSTest/DeviceODView.cs#L827). 
Should this not be the datatype of the parent? Also inheriting accessType and PDOtype would be handy.

I'm not sure about this, so no pull request yet ;-)

**Comment by robincornelius** [comment]
Yes it probably should. Because you can easily end up loading files that do not specify data types for child objects, if the code finds a unknown data type and parent!=null it will always use the parent data type. So nothing bad is currently happening.

However we really should try to get the datatypes correct at the UI level and the protection against null child items should be at the import level. If i cleaned up this it would remove a fair chunk of code that is only there to deal with bad situations such as UNKNOWN datatypes ;-)

I'm currently between PCs so may take a day or two before i can get any coding done
