### ISSUE TITLE
Export CanOpenNode c file fails if subindex contains the character "%"

### ISSUE THREAD

**Issue by trojanobelix** [robincornelius/libedssharp#53]
e.g. if the sub index name is
"Actual alcohol value in vol.-%"

**Comment by robincornelius** [comment]
make_cname() fails when special characters are present. Mostly because of the splitting Regex.Split(name,@"[\W]+") and an unchecked direct substring access.

Its actually the - not the % causing the issue and i did a simple fix but it still fails for things like -test- etc so needs some more work to come up with a cleaner solution. May be strip special characters first as they cannot be used in c variable names anyway.
